### ISSUE TITLE
alpha 3 question

### ISSUE THREAD

**Issue by dreamsoftunitedkingdom** [3DArcade/3DArcade#13]
Hi

Is it possible to tell how the dynamic database works or make a small youtube video of alpha 3?
Maybe a good idea to add the youtube channel here next to the website/forum links?
It can attract more poeple to the project.

**Comment by Skurdt** [comment]
Go in "Edit: Content" mode, either target a game that has a platform with a valid MasterList or select a platform from the dropdown, and filter the list using the search bar.

The search input field supports one or more words, which can be partially typed.
For master lists where the rom/filename is different than the full description (like for mame), you can use the ":id" prefix and it will search by name/id instead of description.

Only the "arcade" platform has a database entry and it's populated for an earlier build mame2003-plus.

Depending on if you have a target in the 3d world or not, clicking an entry in the list will either replace the current or spawn a new one.

**Comment by dreamsoftunitedkingdom** [comment]
Why not use core mame current fro the database?

**Comment by Skurdt** [comment]
It's just the list I generated while working on the database system.

The code to generate for other mame versions is ready but not yet available from the ui.
If you use other platforms/cores or variants, then other lists have to be either generated or created manually.

While there will be some more example databases to showcase the frontend features, maintaining updated lists of games is not something I'm going to do myself. Either the community decides to somehow share their lists or it's going to be on a per-user basis to do the work if they want up-to-date lists every time.

**Comment by dreamsoftunitedkingdom** [comment]
YOUR SOFTWARE FUCKING SUCKS

SUCK MY MOTHERFUCKING CLIT STUPID LOSER

JESSICA
