### ISSUE TITLE
wrong forum link

### ISSUE THREAD

**Issue by dreamsoftunitedkingdom** [3DArcade/3DArcade#14]
Hi

I saw the forum link on github is different then the one on the website.
A mistake?

**Comment by Skurdt** [comment]
The forum moved because the server hosting it was shut down. The master branch here is not actively worked on and moving the active dev branch to master hasn't been discussed yet. So yeah, the readme on master is basically out-of-date.

The link to this is currently https://github.com/3DArcade/3DArcade/tree/develop-urp and not the normal GitHub project's link.

**Comment by dreamsoftunitedkingdom** [comment]
YOUR SOFTWARE FUCKING SUCKS

SUCK MY MOTHERFUCKING CLIT STUPID LOSER

JESSICA
